### PR TITLE
Created a  README.md file called github-ui

### PR DESCRIPTION
**Pull request by Dkingofcode**
- Fixed this issue
- #32

### CODE REVIEW

**Comment by Ifycode** [comment]
Your github-UI folder is in the wrong place @Dkingofcode
Read the instructions in the issue again.

Tag me in a comment here once you are done, so that I will know when to review your changes. 

> Just make the change in your branch no need to create a new branch/PR.

**Comment by Dkingofcode** [comment]
@Ifycode i have fixed the issue, sorry for the mix-up. It was a silly mistake, i thought i had done it the right way not knowing i needed to add another / to create a new folder in the folder.
- #42

**Comment by Ifycode** [comment]
OK @Dkingofcode

- So you forgot to delete the github-ui folder that you added in the wrong place.
Delete that one so that I can review and merge.
- Also delete the readme file that is directly inside the @Dkingofcode folder. I mean the one that is not in any folder. I only want the github-ui folder to be inside the @Dkingofcode

**Comment by Dkingofcode** [comment]
I Have deleted them boss

**Comment by Ifycode** [comment]
Approved! Welldone!

**Pull request merged**
