### PR TITLE
Rename set-1/README.md to Oyenuga17/README.md

### PR DESCRIPTION
**Pull request by oyenuga17**
- #19

### CODE REVIEW

**Comment by Ifycode** [comment]
@oyenuga17 Neatly done. But you did not name the folder correctly. Use the exact casing in your Github user name and then the @ should also be there too. Check the issue instructions again. You can also check example folders in the develop branch to see other folders added by me and one other person.

Also, you don't need to create a new PR. Just change it in your `change-folder-name` branch, and it will automatically reflect in this PR.

**Comment by oyenuga17** [comment]
Ahh, i will fix it now i am just seeing this

**Comment by Ifycode** [comment]
👍🏽 Approved!

**Comment by oyenuga17** [comment]
Thank you !

**Pull request merged**
