### PR TITLE
Fix: Convert Part 1 texts to links in training repo readme

### PR DESCRIPTION
**Pull request by oyenuga17**
**This pull request makes the following changes:**
* Fixes issue Ifycode/git-github-training-resource#5

**Checklist:**
- [x] I have created an issue for this solution I am submitting
- [x] I created a new branch from the correct branch and made my changes in the new branch created
- [x] My pull request is sent to the correct base branch in the original git-github-training repo
- [x] I have linked the issue I worked on to this pull request submitted by me
- [x] File(s) or folder(s) now contain changes as specified in the issue i worked on
- [x] I certify that I ran my checklist.

Ping @Ifycode/git-github-training

### CODE REVIEW

**Comment by oyenuga17** [comment]
I have  made chnages please review

**Comment by Ifycode** [comment]
@oyenuga17
You linked the wrong issue.

Use this below, it will give you the correct link
````
* Fixes issue Ifycode/git-github-training-resource#5
````

**Comment by oyenuga17** [comment]
Okay I will get to it immediately

**Comment by Ifycode** [comment]
Also @oyenuga17, change the title of your pull request to reflect the issue you worked on. Change it from **convert texts to link in training Repo** to **Fix: Convert Part 1 texts to links in training repo readme**

**Comment by oyenuga17** [comment]
I have made corrections @Ifycode

**Comment by oyenuga17** [comment]
Okay  I will

**Review by Ifycode — APPROVED** [review]
💯👍

**Pull request merged**
